### ISSUE TITLE
I did not get

### ISSUE THREAD

**Issue by SudoDios** [trinopoty/socket.io-server-java#15]
The document is not complete.
How do we start a server now ?
How do we specify the IP address and port ?

**Comment by trinopoty** [comment]
I'm assuming you're coming from node.js because last time someone asked this, he was.
This is not a standalone server. You need to configure any of the available java web servers (I use Tomcat personally) and deploy a project that calls into this library using the provided api. How to go about actually doing that is outside the scope of the documentation.
