### ISSUE TITLE
Is Socket.io-server is compatible  with netty server ?

### ISSUE THREAD

**Issue by SaraAadilKhan** [trinopoty/socket.io-server-java#31]
Hi @trinopoty / @oddmario 
Is Socket.io-server is compatible  with netty server and whether it is feasible or not to use with the netty server  and if yes  whether the functionality that is provided in jetty server(setting the context and all) can be done for netty server as well

**Comment by SaraAadilKhan** [comment]
Hi @trinopoty 
If it can be done then please share any demo project for netty - io.netty server

**Comment by trinopoty** [comment]
Hi,
Sorry for the delayed response. I was traveling for a while.
This project does not support netty. But, there is a different project that's built for netty.
You can find it here: https://github.com/mrniko/netty-socketio

**Comment by trinopoty** [comment]
Netty does not follow the standard servlet model as far as I'm aware. While this is not directly supported, it could be possible to construct a wrapper around netty in the case of polling. As for websocket, that could be supported with a thin wrapper as well.

The jetty support library is only required if you're using jetty embedded with manual configuration. Since we use jetty for the integration tests, it made sense to just include the code as a separate library.

If you wish to use mrniko's netty implementation, there is a demo project here: https://github.com/mrniko/netty-socketio-demo

If you wish to adapt this library to netty, you'll need to come up with the wrapper yourself. I could also take a look and give you pointers given some time.

**Comment by SaraAadilKhan** [comment]
Hi @trinopoty 

Thank you for your response

**Comment by trinopoty** [comment]
Hi,
Unfortunately, I haven't used the netty socket.io library and am unable to answer your question.

**Comment by SZahera** [comment]
Hi @trinopoty 
What will be the compatible client with this SocketIoServer or any reference link for this?

**Comment by trinopoty** [comment]
Hi,
All major versions of the server library is compatible with all major versions of the client library.
For instance, v3 of the server library supports any v3 of the client library.
